name: todo
description: "A new Flutter project."


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  uuid: ^4.3.2
  flutter_svg: ^2.0.9
  cloud_firestore: ^4.15.5
  firebase_core: ^2.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/CheckCircle.svg
    - assets/icons/Pencil.svg
    - assets/icons/Trash.svg
    - assets/icons/Calendar.svg
    - assets/icons/All.svg